FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 4200
CMD ["npm", "start", "--", "--host=0.0.0.0"]

#Comandos: sudo docker compose down
#Comandos: sudo docker compose build --no-cache
#Comandos: sudo docker compose up
